/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases"];
        put?: never;
        /** Create Case */
        post: operations["create_case"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{slug}/ai-attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Ai Attempt */
        post: operations["create_ai_attempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{slug}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Case */
        post: operations["approve_case"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{slug}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Attempt */
        post: operations["create_attempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{slug}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case Insights */
        get: operations["get_case_insights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{slug}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reveal Options */
        post: operations["reveal_options"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{slug}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case Review */
        get: operations["get_case_review"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Case */
        post: operations["extract_case"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiAttemptRequest */
        AiAttemptRequest: {
            /** Model */
            model?: string | null;
            provider: components["schemas"]["Provider"];
        };
        /** AiAttemptSummary */
        AiAttemptSummary: {
            /** Attempt Id */
            attempt_id: number;
            calibration: components["schemas"]["Calibration"];
            /** Confidence */
            confidence: number;
            /** Cost Usd */
            cost_usd: number;
            /** Diagnosis Correct */
            diagnosis_correct: boolean;
            /** Diagnosis Text */
            diagnosis_text: string;
            /** Label */
            label: string;
            /** Latency Ms */
            latency_ms: number;
            /** Max Points */
            max_points: number;
            /** Model */
            model: string;
            /** Points */
            points: number;
            /** Provider */
            provider: string;
        };
        /** AnswerKey */
        AnswerKey: {
            /** Accepted Answers */
            accepted_answers: string[];
            final_diagnosis: components["schemas"]["Diagnosis"];
            /** Stages */
            stages: components["schemas"]["AnswerKeyStage"][];
        };
        /** AnswerKeyOption */
        AnswerKeyOption: {
            /** Feedback */
            feedback?: string | null;
            /** Is Correct */
            is_correct: boolean;
            /** Is Harmful */
            is_harmful: boolean;
            /** Key */
            key: string;
            /** Reveal */
            reveal?: string | null;
            /** Text */
            text: string;
        };
        /** AnswerKeyStage */
        AnswerKeyStage: {
            /** Explanation */
            explanation: string;
            /** Options */
            options?: components["schemas"]["AnswerKeyOption"][];
            /** Prompt */
            prompt: string;
            stage: components["schemas"]["DecisionStage"];
        };
        /** ApproveResponse */
        ApproveResponse: {
            review_status: components["schemas"]["ReviewStatus"];
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            /** Slug */
            slug: string;
        };
        /** AttemptIn */
        AttemptIn: {
            /** Choices */
            choices?: {
                [key: string]: string[];
            };
            /** Confidence */
            confidence: number;
            /**
             * Diagnosis Text
             * @default
             */
            diagnosis_text: string;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /** AttemptResult */
        AttemptResult: {
            /** Attempt Id */
            attempt_id: number;
            /** Benchmarks */
            benchmarks?: components["schemas"]["Benchmark"][];
            /** Case Slug */
            case_slug: string;
            /** Cohort Is Simulated */
            cohort_is_simulated: boolean;
            /** Cohort Size */
            cohort_size: number;
            diagnosis: components["schemas"]["DiagnosisResult"];
            final_diagnosis: components["schemas"]["Diagnosis"];
            /** Harmful */
            harmful: number;
            /** Histogram */
            histogram: components["schemas"]["HistogramBin"][];
            /** Max Points */
            max_points: number;
            /** Missed */
            missed: number;
            /** Percentile */
            percentile?: number | null;
            /** Points */
            points: number;
            /** Right */
            right: number;
            /** Stages */
            stages: components["schemas"]["DebriefStage"][];
            /** Total Decisions */
            total_decisions: number;
            /** Wrong */
            wrong: number;
        };
        /**
         * Benchmark
         * @description An AI model that played the same case blinded (latest attempt per model).
         */
        Benchmark: {
            calibration: components["schemas"]["Calibration"];
            /** Confidence */
            confidence: number;
            /** Diagnosis Correct */
            diagnosis_correct: boolean;
            /** Label */
            label: string;
            /** Max Points */
            max_points: number;
            /** Model */
            model: string;
            /** Points */
            points: number;
            /** Provider */
            provider: string;
        };
        /**
         * Calibration
         * @enum {string}
         */
        Calibration: "overconfident" | "underconfident" | "calibrated";
        /** CaseCreated */
        CaseCreated: {
            /** Created */
            created: boolean;
            /** Id */
            id: number;
            /** Slug */
            slug: string;
        };
        /** CaseInsights */
        CaseInsights: {
            /** Benchmarks */
            benchmarks?: components["schemas"]["Benchmark"][];
            /** Cohort Is Simulated */
            cohort_is_simulated: boolean;
            /** Cohort Size */
            cohort_size: number;
            /** Diagnosis Accuracy */
            diagnosis_accuracy?: number | null;
            /** Key Tests */
            key_tests?: components["schemas"]["KeyTestEffect"][];
            /** Slug */
            slug: string;
            /** Stages */
            stages?: components["schemas"]["InsightStage"][];
            /** Title */
            title: string;
            /** Top Wrong Diagnoses */
            top_wrong_diagnoses?: components["schemas"]["WrongDiagnosis"][];
        };
        /** CasePublic */
        CasePublic: {
            /** Chief Complaint */
            chief_complaint: string;
            difficulty: components["schemas"]["Difficulty"];
            /** Estimated Minutes */
            estimated_minutes: number;
            /** Id */
            id: number;
            patient: components["schemas"]["Patient"];
            review_status: components["schemas"]["ReviewStatus"];
            /** Slug */
            slug: string;
            source_kind: components["schemas"]["SourceKind"];
            /** Specialty */
            specialty: string;
            /** Stages */
            stages: components["schemas"]["PublicStage"][];
            /** Title */
            title: string;
            /** Vignette */
            vignette: string;
        };
        /** CaseReview */
        CaseReview: {
            answer_key: components["schemas"]["AnswerKey"];
            /** Checklist */
            checklist: components["schemas"]["ReviewChecklistItem"][];
            review_status: components["schemas"]["ReviewStatus"];
            /** Slug */
            slug: string;
            source: components["schemas"]["ReviewSource"];
            /** Title */
            title: string;
        };
        /** CaseSource */
        CaseSource: {
            kind: components["schemas"]["SourceKind"];
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Provider */
            provider?: string | null;
            /** Text */
            text?: string | null;
        };
        /** CaseSummary */
        CaseSummary: {
            /** Attempts Count */
            attempts_count: number;
            /** Chief Complaint */
            chief_complaint: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decision Count */
            decision_count: number;
            difficulty: components["schemas"]["Difficulty"];
            /** Estimated Minutes */
            estimated_minutes: number;
            /** Id */
            id: number;
            patient: components["schemas"]["Patient"];
            review_status: components["schemas"]["ReviewStatus"];
            /** Slug */
            slug: string;
            source_kind: components["schemas"]["SourceKind"];
            /** Specialty */
            specialty: string;
            /** Title */
            title: string;
        };
        /**
         * CheckStatus
         * @enum {string}
         */
        CheckStatus: "ok" | "warn" | "fail";
        /** ClinicalCase */
        ClinicalCase: {
            /** Chief Complaint */
            chief_complaint: string;
            /** Decisions */
            decisions: components["schemas"]["Decision"][];
            /** Differential */
            differential?: components["schemas"]["Diagnosis"][];
            difficulty: components["schemas"]["Difficulty"];
            /** Estimated Minutes */
            estimated_minutes: number;
            final_diagnosis: components["schemas"]["Diagnosis"];
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /** Measurements */
            measurements?: components["schemas"]["Measurement"][];
            patient: components["schemas"]["Patient"];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            source?: components["schemas"]["CaseSource"] | null;
            /** Specialty */
            specialty: string;
            /** Title */
            title: string;
            /** Vignette */
            vignette: string;
        };
        /** DebriefOption */
        DebriefOption: {
            /** Chosen */
            chosen: boolean;
            /** Feedback */
            feedback?: string | null;
            /** Is Harmful */
            is_harmful: boolean;
            /** Key */
            key: string;
            /** Pick Rate */
            pick_rate?: number | null;
            /** Reveal */
            reveal?: string | null;
            state: components["schemas"]["OptionState"];
            /** Text */
            text: string;
        };
        /** DebriefStage */
        DebriefStage: {
            /** Explanation */
            explanation?: string | null;
            /** Hint */
            hint: string;
            /** Items */
            items?: components["schemas"]["StageItem"][];
            key: components["schemas"]["Stage"];
            /**
             * Kind
             * @enum {string}
             */
            kind: "given" | "decision";
            /** Label */
            label: string;
            /**
             * Max Points
             * @default 0
             */
            max_points: number;
            /**
             * Missed
             * @default 0
             */
            missed: number;
            /** Number */
            number: number;
            /** Options */
            options?: components["schemas"]["DebriefOption"][];
            /**
             * Points
             * @default 0
             */
            points: number;
            /**
             * Right
             * @default 0
             */
            right: number;
            /** Scored */
            scored: boolean;
            /**
             * Wrong
             * @default 0
             */
            wrong: number;
        };
        /** Decision */
        Decision: {
            /** Accepted Answers */
            accepted_answers?: string[];
            /** Explanation */
            explanation: string;
            /** Options */
            options?: components["schemas"]["Option"][];
            /** Prompt */
            prompt: string;
            stage: components["schemas"]["DecisionStage"];
        };
        /**
         * DecisionStage
         * @enum {string}
         */
        DecisionStage: "interview" | "differential" | "workup" | "diagnosis" | "treatment";
        /** Diagnosis */
        Diagnosis: {
            /** Evidence */
            evidence?: string | null;
            /** Icd10 */
            icd10?: string | null;
            /** Name */
            name: string;
        };
        /** DiagnosisResult */
        DiagnosisResult: {
            /** Answered */
            answered: boolean;
            calibration: components["schemas"]["Calibration"];
            /** Confidence */
            confidence: number;
            /** Correct */
            correct: boolean;
            /**
             * Hedged
             * @default false
             */
            hedged: boolean;
            /** Your Text */
            your_text: string;
        };
        /**
         * Difficulty
         * @enum {string}
         */
        Difficulty: "easy" | "medium" | "hard";
        /** EvidenceSpan */
        EvidenceSpan: {
            /** End */
            end?: number | null;
            /** Grounded */
            grounded: boolean;
            /** Path */
            path: string;
            /** Quote */
            quote: string;
            /** Start */
            start?: number | null;
        };
        /** ExtractRequest */
        ExtractRequest: {
            /** Model */
            model?: string | null;
            /** @default gemini */
            provider: components["schemas"]["Provider"];
            /** Text */
            text: string;
        };
        /** ExtractResponse */
        ExtractResponse: {
            case: components["schemas"]["ClinicalCase"];
            /** Grounded Ratio */
            grounded_ratio: number;
            /** Model */
            model: string;
            /** Phi */
            phi: components["schemas"]["PhiCount"][];
            /** Prompt Version */
            prompt_version: string;
            provider: components["schemas"]["Provider"];
            /** Source Text */
            source_text: string;
            /** Spans */
            spans: components["schemas"]["EvidenceSpan"][];
            usage: components["schemas"]["Usage"];
            /** Warnings */
            warnings: string[];
        };
        /** Finding */
        Finding: {
            category: components["schemas"]["FindingCategory"];
            /** Evidence */
            evidence?: string | null;
            /** Text */
            text: string;
        };
        /**
         * FindingCategory
         * @enum {string}
         */
        FindingCategory: "symptom" | "history" | "medication" | "allergy" | "social" | "family" | "exam" | "imaging" | "procedure";
        /**
         * Flag
         * @enum {string}
         */
        Flag: "low" | "normal" | "high" | "abnormal";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistogramBin */
        HistogramBin: {
            /** Count */
            count: number;
            /** Points */
            points: number;
        };
        /** InsightOption */
        InsightOption: {
            /** Is Correct */
            is_correct: boolean;
            /** Is Harmful */
            is_harmful: boolean;
            /** Key */
            key: string;
            /** Pick Rate */
            pick_rate: number;
            /** Text */
            text: string;
        };
        /** InsightStage */
        InsightStage: {
            /** Label */
            label: string;
            /** Missed Correct */
            missed_correct?: components["schemas"]["MissedOption"][];
            /** Options */
            options?: components["schemas"]["InsightOption"][];
            stage: components["schemas"]["DecisionStage"];
        };
        /**
         * KeyTestEffect
         * @description Diagnostic accuracy of those who ordered a correct work-up option vs those who did not.
         */
        KeyTestEffect: {
            /** Chose Rate */
            chose_rate: number;
            /** Dx Accuracy If Chosen */
            dx_accuracy_if_chosen?: number | null;
            /** Dx Accuracy If Not */
            dx_accuracy_if_not?: number | null;
            /** Key */
            key: string;
            /** Text */
            text: string;
        };
        /** Measurement */
        Measurement: {
            /** Evidence */
            evidence?: string | null;
            flag?: components["schemas"]["Flag"] | null;
            kind: components["schemas"]["MeasurementKind"];
            /** Name */
            name: string;
            /** Unit */
            unit?: string | null;
            /** Value */
            value?: number | null;
            /** Value Text */
            value_text?: string | null;
        };
        /**
         * MeasurementKind
         * @enum {string}
         */
        MeasurementKind: "vital" | "lab";
        /** MissedOption */
        MissedOption: {
            /** Key */
            key: string;
            /** Missed Rate */
            missed_rate: number;
            /** Text */
            text: string;
        };
        /**
         * MultiSelectStage
         * @enum {string}
         */
        MultiSelectStage: "interview" | "differential" | "workup" | "treatment";
        /** Option */
        Option: {
            /** Feedback */
            feedback?: string | null;
            /** Is Correct */
            is_correct: boolean;
            /**
             * Is Harmful
             * @default false
             */
            is_harmful: boolean;
            /** Key */
            key: string;
            /** Reveal */
            reveal?: string | null;
            /** Text */
            text: string;
        };
        /**
         * OptionState
         * @enum {string}
         */
        OptionState: "right" | "wrong" | "missed" | "neutral";
        /** Patient */
        Patient: {
            /** Age Years */
            age_years?: number | null;
            /** Display Name */
            display_name?: string | null;
            /** @default unknown */
            sex: components["schemas"]["Sex"];
        };
        /** PhiCount */
        PhiCount: {
            /** Count */
            count: number;
            /** Label */
            label: string;
        };
        /**
         * ProblemDetail
         * @description RFC 9457 problem details, returned for every error.
         */
        ProblemDetail: {
            /** Detail */
            detail?: string | null;
            /** Errors */
            errors?: {
                [key: string]: unknown;
            }[] | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /**
         * Provider
         * @enum {string}
         */
        Provider: "gemini" | "claude";
        /** PublicOption */
        PublicOption: {
            /** Key */
            key: string;
            /** Text */
            text: string;
        };
        /** PublicStage */
        PublicStage: {
            /** Hint */
            hint: string;
            /** Input */
            input?: ("multi_select" | "free_text") | null;
            /** Items */
            items?: components["schemas"]["StageItem"][];
            key: components["schemas"]["Stage"];
            /**
             * Kind
             * @enum {string}
             */
            kind: "given" | "decision";
            /** Label */
            label: string;
            /** Number */
            number: number;
            /** Options */
            options?: components["schemas"]["PublicOption"][];
            /** Prompt */
            prompt?: string | null;
            /** Scored */
            scored: boolean;
        };
        /** RevealIn */
        RevealIn: {
            /** Option Keys */
            option_keys: string[];
            /**
             * Stage
             * @enum {string}
             */
            stage: "interview" | "workup";
        };
        /** RevealOut */
        RevealOut: {
            /** Key */
            key: string;
            /** Reveal */
            reveal: string;
        };
        /** ReviewChecklistItem */
        ReviewChecklistItem: {
            /** Detail */
            detail: string;
            /** Id */
            id: string;
            /** Items */
            items?: string[];
            /** Label */
            label: string;
            status: components["schemas"]["CheckStatus"];
        };
        /** ReviewSource */
        ReviewSource: {
            kind: components["schemas"]["SourceKind"];
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Provider */
            provider?: string | null;
        };
        /**
         * ReviewStatus
         * @description LLM-authored cases start as drafts; only a physician review approves them.
         * @enum {string}
         */
        ReviewStatus: "draft" | "approved";
        /**
         * Sex
         * @enum {string}
         */
        Sex: "female" | "male" | "other" | "unknown";
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "manual" | "llm";
        /**
         * Stage
         * @enum {string}
         */
        Stage: "presenting_complaint" | "history" | "interview" | "examination" | "differential" | "workup" | "results" | "diagnosis" | "treatment";
        /** StageItem */
        StageItem: {
            /** Category */
            category: string;
            flag?: components["schemas"]["Flag"] | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "finding" | "measurement";
            /** Text */
            text: string;
            /** Unit */
            unit?: string | null;
            /** Value */
            value?: string | null;
            /**
             * Withheld
             * @default false
             */
            withheld: boolean;
        };
        /** Usage */
        Usage: {
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WrongDiagnosis */
        WrongDiagnosis: {
            /** Count */
            count: number;
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_cases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSummary"][];
                };
            };
        };
    };
    create_case: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClinicalCase"];
            };
        };
        responses: {
            /** @description Identical case already stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseCreated"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseCreated"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_case: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasePublic"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create_ai_attempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiAttemptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiAttemptSummary"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    approve_case: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_attempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_case_insights: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseInsights"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_options: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevealIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevealOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_case_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseReview"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_case: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
